import 'package:flutter/material.dart';
import 'package:pharmacy/widget/by_city_card.dart';

class ByCity extends StatefulWidget {
  @override
  _ByCityState createState() => _ByCityState();
}

class _ByCityState extends State<ByCity> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("By City"),
        centerTitle: true,
        backgroundColor: Colors.red,
      ),
      body: ListView(
        children: [
          byCityCard("Adana", context,"01"),
          byCityCard("Adıyaman", context,"02"),
          byCityCard("Afyon", context,"03"),
          byCityCard("Ağrı", context,"04"),
          byCityCard("Amasya", context,"05"),
          byCityCard("Ankara", context,"06"),
          byCityCard("Antalya", context,"07"),
          byCityCard("Artvin", context,"08"),
          byCityCard("Aydın", context,"09"),
          byCityCard("Balıkesir", context,"10"),
          byCityCard("Bilecik", context,"11"),
          byCityCard("Bingöl", context,"12"),
          byCityCard("Bitlis", context,"13"),
          byCityCard("Bolu", context,"14"),
          byCityCard("Burdur", context,"15"),
          byCityCard("Bursa", context,"16"),
          byCityCard("Çanakkale", context,"17"),
          byCityCard("Çankırı", context,"18"),
          byCityCard("Çorum", context,"19"),
          byCityCard("Denizli", context,"20"),
          byCityCard("Diyarbakır", context,"21"),
          byCityCard("Edirne", context,"22"),
          byCityCard("Elazığ", context,"23"),
          byCityCard("Erzincan", context,"24"),
          byCityCard("Erzurum", context,"25"),
          byCityCard("Eskişehir", context,"26"),
          byCityCard("Gaziantep", context,"27"),
          byCityCard("Giresun", context,"28"),
          byCityCard("Gümüşhane", context,"29"),
          byCityCard("Hakkari", context,"30"),
          byCityCard("Hatay", context,"31"),
          byCityCard("Isparta", context,"32"),
          byCityCard("Mersin", context,"33"),
          byCityCard("İstanbul", context,"34"),
          byCityCard("İzmir", context,"35"),
          byCityCard("Kars", context,"36"),
          byCityCard("Kastamonu", context,"37"),
          byCityCard("Kayseri", context,"38"),
          byCityCard("Kırklareli", context,"39"),
          byCityCard("Kırşehir", context,"40"),
          byCityCard("Kocaeli", context,"41"),
          byCityCard("Konya", context,"42"),
          byCityCard("Kütahya", context,"43"),
          byCityCard("Malatya", context,"44"),
          byCityCard("Manisa", context,"45"),
          byCityCard("K.Maraş", context,"46"),
          byCityCard("Mardin", context,"47"),
          byCityCard("Muğla", context,"48"),
          byCityCard("Muş", context,"49"),
          byCityCard("Nevşehir", context,"50"),
          byCityCard("Niğde", context,"51"),
          byCityCard("Ordu", context,"52"),
          byCityCard("Rize", context,"53"),
          byCityCard("Sakarya", context,"54"),
          byCityCard("Samsun", context,"55"),
          byCityCard("Siirt", context,"56"),
          byCityCard("Sinop", context,"57"),
          byCityCard("Sivas", context,"58"),
          byCityCard("Tekirdağ", context,"59"),
          byCityCard("Tokat", context,"60"),
          byCityCard("Trabzon", context,"61"),
          byCityCard("Tunceli", context,"62"),
          byCityCard("Şanlıurfa", context,"63"),
          byCityCard("Uşak", context,"64"),
          byCityCard("Van", context,"65"),
          byCityCard("Yozgat", context,"66"),
          byCityCard("Zonguldak", context,"67"),
          byCityCard("Aksaray", context,"68"),
          byCityCard("Bayburt", context,"69"),
          byCityCard("Kırıkkale", context,"70"),
          byCityCard("Batman", context,"71"),
          byCityCard("Şırnak", context,"72"),
          byCityCard("Bartın", context,"73"),
          byCityCard("Ardahan", context,"74"),
          byCityCard("Iğdır", context,"75"),
          byCityCard("Yalova", context,"76"),
          byCityCard("Karabük", context,"77"),
          byCityCard("Kilis", context,"78"),
          byCityCard("Osmaniye", context,"79"),
          byCityCard("Düzce", context,"80"),
        ],
      ),
    );
  }
}
